apiVersion: v2
name: kube-karp
description: Easily add a floating virtual IP to a k8s cluster for load balancing
keywords:
  - "ucarp"
  - "carp"
  - "vrrp"
  - "load balancing"
  - "vip"
  - "virtual ip"
  - "floating ip"
home: https://github.com/immanuelfodor/kube-karp
maintainers:
  - name: Imm√°nuel Fodor
    url: https://fodor.it

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.0.3
